### PR TITLE
remove dualhook and add discord development

### PR DESCRIPTION
**Pull request by ilyigna**
They call me the pine cone tampon, because I make women extremely uncomfortable.

### CODE REVIEW

**Comment by calworld** [comment]
doener homo sex

**Comment by ZJ2** [comment]
wow dualhooked!!! who would have known

**Comment by calworld** [comment]
doenerium u have a good talent coding but yo bitch ass decides to dual hook a stealer dumb ahh nein nein

**Comment by calworld** [comment]
nigga its detected

**Pull request closed without merging**
